### ISSUE TITLE
A silly question: Can we apply PETPVC to DWIs(more specifically NODDI) data

### ISSUE THREAD

**Issue by anbai106** [UCL/PETPVC#26]
Hi, 
Thanks for you work, finally, I installed PETPVC on my Mac, I saw an poster in FreeSurfer who said that this tool can also be used also on DTI maps like this:

> mri_gtmpvc --i subject/dtrecon/adc.nii.gz --reg
>  subject/dtrecon/register.lta --psf 0 --seg subject/mri/gtmseg.mgz
>  --default-seg-merge --auto-mask PSF .01 --mgx 0.25 --o
>  subject/dtrecon/adc.pvc.mgz --no-rescale

So do you think this tool works well for diffusion data (FA)??

More over, if I got NODDI maps(ficvf and odi), can I run this tool to correct the partial volume effect? because I would like to project the ficvf and odi signal onto the T1 cortical cortex surface so the partial volume effect is a problem??

Any suggestion would be appreciated

Hao

**Comment by bathomas** [comment]
Hi,

In principle, yes. However, I should perhaps clarify that the term ***partial volume effect*** refers to a different phenomenon in PET compared to MRI. PVE in PET is mainly due to the spatial resolution of the scanner. In MR, PVE tends to describe the fact that multiple tissues can exist within the same voxel (this is sometimes called ***tissue-fraction effect***). 

You will notice the ```--psf 0``` argument. I'm not very familiar with the PVC tools in FreeSurfer, but I presume that it means no correction for spatial smoothing will be applied. So the command quoted above appears to be correcting for tissue-fraction effect only.  I believe this is the appropriate thing to do for the diffusion data, though I am not really in a position to tell you whether GTM is the best approach for this application. The GTM implementation in the PETPVC toolbox will produce tissue-fraction corrected mean values (pass ```-x 0 -y 0 -z 0```). I would expect the output to be similar to ```mri_gtmpvc```. 

I don't know anything about NODDI maps, so I can't give you an answer.
