### ISSUE TITLE
VOIs masks based on Hammers atlas

### ISSUE THREAD

**Issue by mattvan83** [UCL/PETPVC#50]
Dear Dr. Thomas,

I would like to apply RBV PVC for AV-45 PET data (healthy controls and AD patients) as suggested by your study (Thomas et al., 2011).

However, not having access to Freesurfer Desikan parcellation I would like to build VOIs masks based on Hammers atlas and SPM12 probabilities tissue maps.

Should I then separate WM from GM in VOIs since in Hammers atlas, both are joined ? Should I re-segment Hammers VOIs into 14 VOIs as described in your paper from 2011?

Thanks for guiding me.

Best regards,
Matthieu

**Comment by bathomas** [comment]
Yes, you should separate WM from GM. The VOI delineation is application (and tracer) dependent really. You may consider using a more detailed parcellation for cortical regions than the 14 used previously. `FS.csv` describes how the FreeSurfer parcellation could be reduced. This should give you an idea of how you might want to go about parcellating the brain from Hammers. Alternatively, you could use the VOIs (once GM/WM separated) as-is, the correction would take longer to perform. You might want to consider iterative Yang (IY) instead of RBV if you have many VOIs.

**Comment by mattvan83** [comment]
Thank you for these precisions.

I have two questions then:
1) Is it better to use more or less VOIs?
2) Shouldn't the VOI delineation be based on the pathology of patients?

**Comment by bathomas** [comment]
1. In principle more is better. 
2. Yes, that's what I meant by application-dependent. For example, in an AD study, you might consider defining VOIs based on say Braak staging.
