### ISSUE TITLE
STC method: algorithm?

### ISSUE THREAD

**Issue by mattvan83** [UCL/PETPVC#52]
Dear Dr. Thomas,

Using different reference regions to intensity normalize my PET images (cerebellum, pons,...), the mean PVC of each reference region is not always available based on the PVC method used.

I was wondering whether STC would be a good alternative to determine the mean PVC of all my reference regions? Which algorithm is based STC on?

Best regards,
Matthieu

**Comment by bathomas** [comment]
This would be interesting to try. STC is conceptually similar to multi-target correction (MTC) (see [Erlandsson et al., Phys. Med. Biol. 57 (2012) R119–R159](https://iopscience.iop.org/article/10.1088/0031-9155/57/21/R119/meta)) except the correction is calculated on a voxel-wise basis rather than using regional means, as in MTC.
