### ISSUE TITLE
difference between iterations (-n) and deconvolution iterations (-k)

### ISSUE THREAD

**Issue by bilgelm** [UCL/PETPVC#53]
If I understand correctly, the -n flag applies to RL, VC, STC, and IY, whereas the -k flag applies to RL and VC only. What is the difference?

**Comment by bathomas** [comment]
The reason the RL and VC methods use the `-k` flags and the others use `-n` is so that you can compound the techniques together in a single command line call. For example, if you wanted to apply IY and then VC (`IY+VC`), then the `-n` refers to the number of `IY` iterations and `-k` is the number of iterations performed during VC deconvolution.

**Comment by bilgelm** [comment]
Thanks!
