### ISSUE TITLE
Have an issue with cmake

### ISSUE THREAD

**Issue by BWWwustl** [UCL/PETPVC#93]
![Capture](https://github.com/UCL/PETPVC/assets/118126504/71ddf812-1baf-4d9d-9dd6-b1a146c766a8)
After I clone the repo and trying to cmake, I got this error. I am pretty new to C++ and don't know what could cause this problem, anyone could help would be appreciate

**Comment by KrisThielemans** [comment]
I think this is because doesn't find your "tool chain". Looks like you are on Windows. What compiler etc did you install? For instance, you could use https://visualstudio.microsoft.com/vs/community/, or https://clang.llvm.org/get_started.html, or you could use WSL.

You need to tell CMake that this is what you're going to use. See for instance https://cmake.org/cmake/help/v3.27/generator/Visual%20Studio%2017%202022.html. Note that when using cmake from the command line, you'd want to do this from a prompt that has the tools in the path (usually called "Powershell for Visual Studio 2022" or so).

Alternatively, you use the binary on https://github.com/UCL/PETPVC/releases. Due to #94 you'll have to use 1.2.10 but that'd be fine.

**Comment by KrisThielemans** [comment]
> Alternatively, you use the binary

Or use conda https://anaconda.org/conda-forge/petpvc

**Comment by BWWwustl** [comment]
Thanks. I used the binary version to install the PETPVC.
